### ISSUE TITLE
 No such file or directory: 'zhen_base/data/result.tsv'

### ISSUE THREAD

**Issue by genbei** [TharinduDR/TransQuest#22]
My settings in `monotransquest_config.py` are as follows：

`SEED = 777
TEMP_DIRECTORY = "zhen_base/data"
RESULT_FILE = "result.tsv"
SUBMISSION_FILE = "predictions.txt"
RESULT_IMAGE = "result.jpg"
GOOGLE_DRIVE = False
DRIVE_FILE_ID = None
MODEL_TYPE = "xlmroberta"
MODEL_NAME = "xlm-roberta-large"

monotransquest_config = {
    'output_dir': 'zhen_base/outputs/',
    "best_model_dir": "zhen_base/outputs/best_model",
    'cache_dir': 'zhen_base/cache_dir/',`

But I found that the `data` folder was not generated at runtime, Generate only `cache_dir`and `outputs` ,that is, there was no prediction of the test set.
By the way, after training the model, I got the best_model. What should I do if I only make predictions

> Traceback (most recent call last):
  File "/home/miniconda3/envs/transquest/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/miniconda3/envs/transquest/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/TransQuest/examples/sentence_level/wmt_2020_task2/zh_en/monotransquest.py", line 99, in <module>
    dev.to_csv(os.path.join(TEMP_DIRECTORY, RESULT_FILE), header=True, sep='\t', index=False, encoding='utf-8')
  File "/home/miniconda3/envs/transquest/lib/python3.7/site-packages/pandas/core/generic.py", line 3403, in to_csv
    storage_options=storage_options,
  File "/home/miniconda3/envs/transquest/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1083, in to_csv
    csv_formatter.save()
  File "/home/miniconda3/envs/transquest/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 234, in save
    storage_options=self.storage_options,
  File "/home/miniconda3/envs/transquest/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'zhen_base/data/result.tsv'

**Comment by TharinduDR** [comment]
Since there was no bug, I am removing the bug label. Please avoid using it
