### ISSUE TITLE
[BUG]404 Client Error: Not Found for url: https://huggingface.co/api/models/temp/outputs/best_model

### ISSUE THREAD

**Issue by genbei** [TharinduDR/TransQuest#31]
I run the monotransquest code, which is good, but when I run `CUDA_VISIBLE_DEVICES=0 python -m examples.sentence_level.wmt_2020_task2.en_zh.siamesetransquest`
, something goes wrong.

> Traceback (most recent call last):
  File "/data/miniconda3/envs/tqtq/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/miniconda3/envs/tqtq/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/TransQuest-master/examples/sentence_level/wmt_2020_task2/en_zh/siamesetransquest.py", line 73, in <module>
    model = SiameseTransQuestModel(siamesetransquest_config['best_model_dir'])
  File "/data/TransQuest-master/transquest/algo/sentence_level/siamesetransquest/run_model.py", line 29, in __init__
    self.model = SiameseTransformer(model_name, args=args)
  File "/data/TransQuest-master/transquest/algo/sentence_level/siamesetransquest/models.py", line 236, in __init__
    transformer_model = Transformer(model_name, max_seq_length=self.args.max_seq_length)
  File "/data/TransQuest-master/transquest/algo/sentence_level/siamesetransquest/models.py", line 48, in __init__
    config = AutoConfig.from_pretrained(model_name_or_path, **model_args, cache_dir=cache_dir)
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 580, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/transformers/configuration_utils.py", line 554, in get_config_dict
    local_files_only=local_files_only,
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/transformers/configuration_utils.py", line 842, in get_configuration_file
    path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/transformers/file_utils.py", line 1952, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/huggingface_hub/hf_api.py", line 603, in list_repo_files
    repo_id, revision=revision, token=token, timeout=timeout
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/huggingface_hub/hf_api.py", line 586, in model_info
    r.raise_for_status()
  File "/data/miniconda3/envs/tqtq/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/temp/outputs/best_model

**Comment by genbei** [comment]
- Cosine-Similarity :       Pearson: nan    Spearman: nan      

I found that when evaluating the model during training，the score is nan, so the best model can't be saved, and further training can't be continued.
